### ISSUE TITLE
Rename `.partial_ord`/`.ord` method to `.partial_lexicographical_ord`/`lexicographical_ord

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/packed_simd#100]
Currently the `.partial_ord` method returns a `PartiallyOrdered<T>` wrapper that implements `PartialOrd`/`Ord` for the vector type, but it does not convey any information about the partial order being implemented. 

I think it would be better to rename this to  `.partial_lexicographical_ord`/`.lexicographical_ord` instead to make that crystal clear. It might be too verbose, but that's the way it is.

**Comment by hdevalence** [comment]
What about `.partial_lex_ord`?

**Comment by gnzlbg** [comment]
Fixed in https://github.com/rust-lang-nursery/packed_simd/pull/105
