### ISSUE TITLE
suboptimal all/any reductions in x86/x86_64

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/packed_simd#103]
cc @TheIronBorn who continuously worked to improve the implementation and did all the work that's contained in this issue.

---

### Rust implementation

Before PR (https://github.com/rust-lang-nursery/packed_simd/pull/66), we had no specialization for SSE4.1, so the 128-bit masks were using SSE2 implementation which is as follows:

```rust
fn all_sse2(x: m32x4) -> bool {
    // _mm_movemask_epi8(a) creates a 16bit mask containing the
    // most significant bit of each byte of `a`. If all
    // bits are set, then all 16 lanes of the mask are
     // true.
    _mm_movemask_epi8(::mem::transmute(x))
    == i32::from(u16::max_value())
}
fn any_sse2(x: m32x4) -> bool {
    _mm_movemask_epi8(::mem::transmute(x)) != 0
}
```

In PR https://github.com/rust-lang-nursery/packed_simd/pull/66 we added a specialization for SSE4.1 which saves one instruction, and implements `all`/`any` as follows:

```rust
fn all_sse41(x: m32x4) -> bool {
    // _mm_test_all_ones(a, a) returns a 1 if all bits of
    // `a` are set, 0 if not.
    _mm_test_all_ones(::mem::transmute(self)) == 1
}
fn any_sse41(x: m32x4) -> bool {
    _mm_test_all_zeros(::mem::transmute(self), ::mem::transmute(self))
     == 0
}
```

### Assembly generated 

With SSE4.1 enabled for **both** (SSE2 and SSE4.1) implementations Rust using LLVM 8 trunk produces (https://rust.godbolt.org/z/50cOH-):

```asm
all_sse2:
  movdqa xmm0, xmmword ptr [rdi]
  pmovmskb eax, xmm0
  cmp eax, 65535
  sete al
  ret

any_sse2:
  movdqa xmm0, xmmword ptr [rdi]
  pmovmskb eax, xmm0
  test eax, eax
  setne al
  ret

all_sse41:
  movdqa xmm0, xmmword ptr [rdi]
  pcmpeqd xmm1, xmm1
  ptest xmm0, xmm1
  setb al
  ret

any_sse41:
  movdqa xmm0, xmmword ptr [rdi]
  ptest xmm0, xmm0
  setne al
  ret
```

Since both are semantically equivalent, the first bug here is that they should produce the exact same machine code but they do not. 

Secondly, the SSE4.1 versions have sub-optimal performance at least on Skylake as shown in the IACA report generated by @TheIronBorn (https://gist.github.com/TheIronBorn/faf896e7b86bf2353e0b915ed5c596e7):

* `ptest` -> Uops: 6, Throughput: 1.49 Cycles
* `movmsk` -> Uops: 5, Throughput: 1.26 Cycles
* `movmsk` (targeted) -> Uops: 4, Throughput: 0.95 Cycles
* `_mm_test_all_zeros` -> Uops: 5, Throughput: 1.22 Cycles

I repeated these on MacOSX (https://gist.github.com/gnzlbg/80d3139393615c18495b1dd7855fc787) and got:

* all SSE2 (`movmsk`) -> Uops: 4, Throughput 1.00 Cycles
* all SSE4.1 (`ptest`) -> Uops: 5, Throughput 1.24 Cycles
* any SSE2 (`movmsk`) -> Uops: 4, Throughput 1.00 Cycles
* any SSE4.1 (`ptest`) -> Uops: 4, Throughput 1.00 Cycles

which are slightly different measurements than what @TheIronBorn obtained (thoughts?).

## LLVM-IR generated

```llvm
define zeroext i1 @all_sse2(<4 x i32>* noalias nocapture readonly dereferenceable(16) %x) unnamed_addr #0 {
  %0 = bitcast <4 x i32>* %x to <16 x i8>*
  %1 = load <16 x i8>, <16 x i8>* %0, align 16
  %2 = tail call i32 @llvm.x86.sse2.pmovmskb.128(<16 x i8> %1) #2
  %3 = icmp eq i32 %2, 65535
  ret i1 %3
}

define zeroext i1 @any_sse2(<4 x i32>* noalias nocapture readonly dereferenceable(16) %x) unnamed_addr #0 {
  %0 = bitcast <4 x i32>* %x to <16 x i8>*
  %1 = load <16 x i8>, <16 x i8>* %0, align 16
  %2 = tail call i32 @llvm.x86.sse2.pmovmskb.128(<16 x i8> %1) #2
  %3 = icmp ne i32 %2, 0
  ret i1 %3
}

define zeroext i1 @all_sse41(<4 x i32>* noalias nocapture readonly dereferenceable(16) %x) unnamed_addr #0 {
  %0 = bitcast <4 x i32>* %x to <2 x i64>*
  %1 = load <2 x i64>, <2 x i64>* %0, align 16
  %2 = tail call i32 @llvm.x86.sse41.ptestc(<2 x i64> %1, <2 x i64> <i64 -1, i64 -1>) #2
  %3 = icmp eq i32 %2, 1
  ret i1 %3
}

define zeroext i1 @any_sse41(<4 x i32>* noalias nocapture readonly dereferenceable(16) %x) unnamed_addr #0 {
  %0 = bitcast <4 x i32>* %x to <2 x i64>*
  %1 = load <2 x i64>, <2 x i64>* %0, align 16
  %2 = tail call i32 @llvm.x86.sse41.ptestz(<2 x i64> %1, <2 x i64> %1) #2
  %3 = icmp eq i32 %2, 0
  ret i1 %3
}
```

## Conclusion

The only advantage of using `ptest` here is that for the `any(m32x4)->bool` implementation, `ptest` produces one instruction less than the equivalent code using `movmsk`. IACA extimates that `movmsk` has the same throughput as `ptest` in that case, and better throughput than `ptest` for the `all(m32x4)->bool` implementation.

An LLVM bug has been reported (https://bugs.llvm.org/show_bug.cgi?id=38788). In the meantime, we might want to fall back to using `movmsk` in the sse4.1 implementation of `all` at least.

**Comment by TheIronBorn** [comment]
The IACA difference is likely because your code doesn’t produce jump instructions. `movmsk` allows a pair of `cmp` and `jmp` instructions to be fussed which is wehere the speed comes from

**Comment by gnzlbg** [comment]
@TheIronBorn so there is nothing that can be done at the LLVM level about this, because we can't really express that the m32x4 which is just a i32x4 internally contains i32s that have been sign-extended from i1, and `ptest` and `movmsk` are only equivalent if that's the case. 

I think we can just fully revert that PR then. What do you think?

**Comment by TheIronBorn** [comment]
Surely if LLVM knows we generated m32x4 from `cmp/eq/lt/etc`?

**Comment by gnzlbg** [comment]
LLVM sadly doesn't know that nor does it have a way to know that yet :/

**Comment by TheIronBorn** [comment]
Maybe I'm misunderstanding something, but each lane of `_mm_cmpeq_epi32(x, y)` can only have all ones or all zeros. Which means LLVM should know it can use any bit per lane for `all/any/none`. 

In any case, I think reverting the PR makes sense.

**Comment by gnzlbg** [comment]
https://bugs.llvm.org/show_bug.cgi?id=38788#c3

> but each lane of _mm_cmpeq_epi32(x, y) can only have all ones or all zeros.

This is correct.

> Which means LLVM should know it can use any bit per lane for all/any/none.

It should, but it currently does not. Currently there is no way implemented to convey this nor propagate it across values (e.g. we want to state this invariant for m32x4 when returned from an opaque function so that even if LLVM cannot look into the function to see how it is generated, it could still assume this).
