### ISSUE TITLE
Latest docs.rs documentation isn't working

### ISSUE THREAD

**Issue by GabrielMajeri** [rust-lang-nursery/packed_simd#110]
The link https://docs.rs/packed_simd/ leads to a 404 error.

docs.rs [fails to build the crate](https://docs.rs/crate/packed_simd/0.2.0/builds/114604), because it uses `repr(transparent)`, which has been stabilised in 1.29,
but their build system is still using Rust 1.28

Similar docs.rs issue: https://github.com/onur/docs.rs/issues/219

It's unfortunate but the main docs.rs developer hasn't been active in a while so it's unknown how long it will take for them to update their compiler.

**Comment by gnzlbg** [comment]
Yeah, sadly there is nothing much that we can do about this until the docs.rs issue is resolved. 

In the mean time, the documentation generated from the master branch is available here and updated on every commit: https://rust-lang-nursery.github.io/packed_simd/packed_simd/

**Comment by tafia** [comment]
docs.rs looks to be working as expected now.
I believe this should be closed, and the comment on the readme removed?
