### ISSUE TITLE
crate_visibility_modifier is not on crates.io

### ISSUE THREAD

**Issue by hsivonen** [rust-lang-nursery/packed_simd#161]
Could you, please, publish a version that contains the [changeset for `crate_visibility_modified`](https://github.com/rust-lang-nursery/packed_simd/commit/ed0021202b5860cd7c68f7906a3062392c37acf8) to crates.io?

**Comment by gnzlbg** [comment]
version `0.3` has been published (https://github.com/rust-lang-nursery/packed_simd/commit/982dd73b3f57b1ef747fe01a328c24d40eecab36) and should work with the latest nightly

**Comment by hsivonen** [comment]
0.3 works. Thank you.
