### ISSUE TITLE
Add mask method to extract the mask as an integer

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/packed_simd#166]
A common operation on masks is converting the vector into an integer where each bit denotes a lane.

**Comment by GabrielMajeri** [comment]
@gnzlbg From what I can understand, I think this might help with #150, specifically:
we can use a mask to track which lanes have diverged, and then convert this mask to an integer which we then directly output as a bitmap.

**Comment by gnzlbg** [comment]
@GabrielMajeri I think that to implement this portably we might want to generate llvm-ir that looks like this (cc @rkruppe - https://gcc.godbolt.org/z/VNbIFQ):

```llvm
define i8 @to_i8(<4 x i32>) {
    %a = trunc <4 x i32> %0 to <4 x i1>
    %b = bitcast <4 x i1> %a to i4
    %c = zext i4 %b to i8
    ret i8 %c
}
```

Since we can't directly use the `<N x i1>` types from Rust, we will probably need to add a rustc intrinsic for this, but that shouldn't be hard.

**Comment by gnzlbg** [comment]
After optimizations, that IR becomes

```llvm
define i8 @m32x4_to_i8_opt(<4 x i32>) {
  %2 = and <4 x i32> %0, <i32 1, i32 1, i32 1, i32 1>
  %a = icmp ne <4 x i32> %2, zeroinitializer
  %b = bitcast <4 x i1> %a to i4
  %c = zext i4 %b to i8
  ret i8 %c
}
```

We could also generate IR like this:

```llvm
define i8  @m32x4_to_i8_2(<4 x i32>) {
  %a = icmp ne <4 x i32> %0, zeroinitializer
  %b = bitcast <4 x i1> %a to i4
  %c = zext i4 %b to i8
  ret i8 %c
}
```

but for some reason the quality of the generated assembly differs significantly, and the unoptimized IR seems to be the best... (https://gcc.godbolt.org/z/I-Sco7):

```asm
m32x4_to_i8: #unoptimizzed
 vpslld $0x1f,%xmm0,%xmm0
 vpsrad $0x1f,%xmm0,%xmm0
 vmovmskps %xmm0,%eax
 retq   
 nop
m32x4_to_i8_opt:
 vpbroadcastd 0x0(%rip),%xmm1        # 19 <m32x4_to_i8_opt+0x9>
 vpand  %xmm1,%xmm0,%xmm0
 vpcmpeqd %xmm1,%xmm0,%xmm0
 vmovmskps %xmm0,%eax
 retq   
 nopw   %cs:0x0(%rax,%rax,1)
m32x4_to_i8_2:
 vpxor  %xmm1,%xmm1,%xmm1
 vpcmpeqd %xmm1,%xmm0,%xmm0
 vpcmpeqd %xmm1,%xmm1,%xmm1
 vpxor  %xmm1,%xmm0,%xmm0
 vmovmskps %xmm0,%eax
 retq   
```
