### ISSUE TITLE
Crates.io crate fails to build on nightly rust

### ISSUE THREAD

**Issue by hdevalence** [rust-lang-nursery/packed_simd#173]
Hi, would it be possible to publish another version of the crate on crates.io? The current one is failing on nightly rust due to a missing `#![feature(crate_visibility_modifier)]` (which is included in the git repo).

**Comment by GabrielMajeri** [comment]
@hdevalence That nightly feature is used to fix the build on the latest nightly. If you want to use a crates.io version which might work with an older nightly, try 0.2

**Comment by hdevalence** [comment]
Oops, I think I got confused between 0.2 and 0.3, sorry! Thanks for the help.
