### ISSUE TITLE
logical and_not instructions support

### ISSUE THREAD

**Issue by burrbull** [rust-lang-nursery/packed_simd#198]
like avx2 PANDN

**Comment by gnzlbg** [comment]
Doesn't

```rust
let x: Simd<[u32; 4]>;
let y: Simd<[u32; 4]>;
let z: Simd<[u32; 4]> = (!x) & y;
```

just work ?

**Comment by burrbull** [comment]
I know that this work, I mean optimized (single instruction) variant.

**Comment by gnzlbg** [comment]
> I mean optimized (single instruction) variant.

If `!x & y` does not produce a single instruction, then that's a bug (would need a MWE to debug it). 

An API for the single instruction already exists in core arch, unless there are cases that are not covered by `!x & y`, I don't see what value would it add to include it here.

**Comment by burrbull** [comment]
> An API for the single instruction already exists in core arch, unless there are cases that are not covered by `!x & y`.

This is what I wanted to hear.
Thanks.

**Comment by gnzlbg** [comment]
@burrbull if you realize that `!x & y` does not uses `pandn`/`vpandn` when it should, please open an issue about that. We might need to fix that in LLVM, but since rust-lang/rust is tracking LLVM trunk already, that shouldn't be too hard.
