### ISSUE TITLE
Compilation failure on latest nightly

### ISSUE THREAD

**Issue by theotherphil** [rust-lang-nursery/packed_simd#203]
Edit: I can build the crate directly, but compilation fails when I add this as a dependency of my crate.
Edit 2: Adding `cfg-if = "0.1.6"` to my crate's Cargo.toml fixes the build, but I'm not sure why I need to explicitly add the indirect dependency.

I'm using version 0.3.1, and the following rustc:

> $ rustup default nightly
> info: using existing install for 'nightly-x86_64-apple-darwin'
> info: default toolchain set to 'nightly-x86_64-apple-darwin'
> 
>   nightly-x86_64-apple-darwin unchanged - rustc 1.33.0-nightly (c76f3c374 2019-01-18)

This gives the following errors and then many many more:

> $ cargo build
>     Blocking waiting for file lock on the registry index
>     Updating crates.io index
>   Downloaded packed_simd v0.3.1
>    Compiling packed_simd v0.3.1
> error[E0432]: unresolved imports `crate::codegen::pointer_sized_int::isize_`, `crate::codegen::pointer_sized_int::usize_`
>  --> /Users/philip/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd-0.3.1/src/codegen/vSize.rs:3:41
>   |
> 3 | use crate::codegen::pointer_sized_int::{isize_, usize_};
>   |                                         ^^^^^^  ^^^^^^ no `usize_` in `codegen::pointer_sized_int`
>   |                                         |
>   |                                         no `isize_` in `codegen::pointer_sized_int`
> 
> error[E0432]: unresolved imports `crate::codegen::pointer_sized_int::isize_`, `crate::codegen::pointer_sized_int::usize_`
>  --> /Users/philip/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd-0.3.1/src/vSize.rs:3:41
>   |
> 3 | use crate::codegen::pointer_sized_int::{isize_, usize_};
>   |                                         ^^^^^^  ^^^^^^ no `usize_` in `codegen::pointer_sized_int`
>   |                                         |
>   |                                         no `isize_` in `codegen::pointer_sized_int`

**Comment by gnzlbg** [comment]
@theotherphil we are in the process of refactoring `core::arch` and `std::detect` in Rust upstream. Once that lands (hopefully today-tomorrow), new versions of `stdsimd` can be released, and `packed_simd` can be updated. Sorry for the downfall in the meantime.

**Comment by gnzlbg** [comment]
I've released version 0.3.2 of `packed_simd`. Everything should work now. Please re-open this issue if that doesn't solve the problem for you.
