### ISSUE TITLE
Provide other trigonometric functions like tanh?

### ISSUE THREAD

**Issue by SuperFluffy** [rust-lang-nursery/packed_simd#225]
Is there a chance that `packed_simd` might expose additional trigonometric functions like `tanh` from `Sleef`? I am particulary interested in `__m256d Sleef_tanhd4_u10(__m256d a);` and friends.

**Comment by gnzlbg** [comment]
Sure, PRs welcome. One just needs to expose them. I can mentor if you want to work on this. A good place to start is to check how the other implemented trigonometric functions are implemented (e.g. `sin`), and try to do the same for those.

**Comment by SuperFluffy** [comment]
Sounds good. I have copied the sin code and am right now trying to figure out where to find the corresponding llvm intrinsics.

**Comment by gnzlbg** [comment]
The "LLVM LangRef" has everything that you need (google that).

**Comment by SuperFluffy** [comment]
I did find sin and cos there, https://llvm.org/docs/LangRef.html#llvm-sin-intrinsic, but not tan or any hyperbolic functions. The most recent version (5h when writing this) also doesn't contain any info on these: https://github.com/llvm-mirror/llvm/blob/master/docs/LangRef.rst

**Comment by gnzlbg** [comment]
I see, well don't despair. Instead of calling LLVM, you can call the Rust method on each of the vector elements, and use sleef when available. We can worry about LLVM later.

**Comment by SuperFluffy** [comment]
Probably I have not understood you correctly, but did I understand you correctly that I should have code akin to the following?

```rust
fn tanh_v4f32(x: f32x4) -> f32x4 {
    let mut buf = [0.0; 4];
    x.write_to_slice_aligned(&mut buf);
    for elem in &mut buf {
        *elem = (*elem).tanh();
    }
    f32x4::from_slice_aligned(&buf)
}
```

Because if yes, this won't work, because `f32::tanh` is provided through Rust's std library, and `packed_simd` is `no_std`.

Or did you mean I should implement tanh only when `sleef` is available?

**Comment by burrbull** [comment]
If you interesting, I've tried to port sleef to Rust https://github.com/burrbull/sleef-rs.
You can find tanh there like f32x4::u35::tanhf(x: f32x4) or f32x4::u10::tanhf(x: f32x4).
But this still requires thorough rework, testing and benchmarking.
What is needed:
1. Feature gates for different platforms, fma, etc.
2. llvm intrinsics, where it's possible.
3. Testing. Started porting from libm [here](https://github.com/burrbull/sleef-rs/tree/test).
4. Tracking of sleef for new functionality.

**Comment by gnzlbg** [comment]
> Because if yes, this won't work, because f32::tanh is provided through Rust's std library, and packed_simd is no_std.

Indeed. You can try to use https://github.com/rust-lang-nursery/libm here instead.

**Comment by SuperFluffy** [comment]
PR updated, thanks for the hint. The errors in the tests are a bit confusing to me. Can you take a look at the code line I added a review for?
