### ISSUE TITLE
Implement conversions and bitcasts per the RFC

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/packed_simd#4]
https://github.com/gnzlbg/rfcs/blob/ppv/text/0000-ppv.md#conversions-and-bitcasts: 

> There are three different ways to convert between vector types.
>
> * `From/Into`: value-preserving widening-conversion between vectors with the same number of lanes. That is, `f32x4` can be converted into` f64x4` using `From`/`Into`, but the opposite is not true because that conversion is not value preserving. The From/Into implementations mirror that of the primitive integer and floating-point types. These conversions can widen the size of the element type, and thus the size of the SIMD vector type. Signed vector types are sign-extended lane-wise, while unsigned vector types are zero-extended lane-wise. The result of these conversions is endian-independent.
>
> * `a`s: non-value preserving truncating-conversions between vectors with the same number of lanes. That is, `f64x4 as f32x4` performs a lane-wise as cast, truncating the values if they would overflow the destination type. The result of these conversions is endian-independent.
> 
> * `unsafe mem::transmute`: bit-casts between vectors with the same size, that is, the vectors do not need to have the same number of lanes. For example, transmuting a `u8x16` into a `u16x8`. Note that while all bit-patterns of the `{i,u,f}` vector types represent a valid vector value, there are many vector mask bit-patterns that do not represent a valid mask. Note also that the result of `unsafe mem::transmute` is endian-dependent (see examples below).

As an extension to the RFC, we should implement the `FromBits`/`IntoBits` of the RFC as a temporary workaround for the lack of a `Compatible` trait that allows performing safe transmutes.

**Comment by gnzlbg** [comment]
The `FromBits`/`IntoBits` traits from `stdsimd` have been implemented in #28 behind the `cargo` feature `--feature into_bits`. 

---

Non-value preserving truncating-conversion will be implemented using similar `FromTrunc`/`IntoTrunc` traits.

**Comment by gnzlbg** [comment]
An alternative to `as` is proposed in RFC2844: https://github.com/rust-lang/rfcs/pull/2484

**Comment by hdevalence** [comment]
Hi, something I'm not clear on from reading the RFC: what is the intended relationship between `ppv` types (like `u32x8`) and platform-dependent vector types from `core::arch` (like an `__m256i`)?

It's extremely useful to be able to write mostly-generic SIMD code (using the `ppv` types), but still be able to use platform-specific instructions (which require platform-dependent types) in a few places. Right now this is possible to do using `IntoBits`; is the plan to keep doing this, or to replace `FromBits`/`IntoBits` with something else?

**Comment by gnzlbg** [comment]
The plan is to replace IntoBits with something better but what that would
be, is not clear yet.

The RFC has a couple of links to the discussions about possible solutions.
Some Fuchsia devs worked on one during the all hands in parents IIRC, but
the most promising ones require compiler support and AFAICT nobody has
worked much on those. They are blocked on better chalk integration IIRC.

**Comment by gnzlbg** [comment]
*Paris, not “parents”.

In the meantime you can either keep using IntoBits, or if you want to
remain maximally forward compatible, you can use mem::transmute.

>

**Comment by gnzlbg** [comment]
I'm closing this since we are not going to implement `as` for simd vectors (we'll use `.cast()` for that instead).
