### ISSUE TITLE
packed simd vectors shall not implement PartialOrd

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/packed_simd#48]
### Pros/Cons of implementing `PartialOrd`

The `PartialOrd` implementation for vectors has the following **disadvantages**:

* It is surprising to new users: new users often do not expect a lexicographical ordering. For example,  they might expect `<` to return `true` only if _all_ lanes of the resulting mask are `true` which is a reasonable expectation to have. 

* Another potentially-surprising consequence of implementing a lexicographical ordering is that both `&[i32]` and `&[i32x4]` implement `PartialOrd` and `Ord` and therefore can be `sort`ed, but the ordering of the elements will be different. 

* If anything I'd see this as an argument in favor of pointwise ordering as it makes such code not compile any more, which is the best possible behavior (better than compiling it but doing something strange).

* New users would often be better served by rewriting their code to just use the vertical comparisons producing masks.

* It is slow: it is an horizontal operation, typically requiring two vertical comparisons (e.g. `<` and `==`), and then a scalar loop over the masks, e.g.: 

    ```rust
    fn lt(&self, other: &Self) -> bool {
        let m_lt = Self::lt(*self, *other);
        let m_eq = Self::eq(*self, *other);
        for i in 0..$id::lanes() {
            if m_eq.extract(i) {
                continue;
            }
            return m_lt.extract(i);
        }
        false
    }
    ```
  Also, there are many generic types that are often instantiated for portable vector types, like `&[f32x4]` where users would probably be better served by the `PartialOrd` implementation for `&[f32]`. 

The **advantages** of providing a `PartialOrd` implementation are:

* It is not trivial to implement it yourself.  
* TODO: summarize other advantages?

### Actionable Improvements

We could significantly reduce the disadvantages while maintaining most of the advantages by:

* Providing methods on the vector types that implement a partial or total order (returning `Ordering` and/or `Option<Ordering>`) without implementing `PartialOrd` for the portable vector types. This would allow users that need a `PartialOrd` implementation to easily write a new type wrapper, and use the inherent method to implement `partial_cmp` or `cmp` for it. This would also allow us to implement multiple different ordering relations for floating point types, where we could provide a `partial_cmp` and `cmp` method implementing a partial and total order, and let the user choose which one they want to use.

* Provide specializations of `PartialOrd` for types commonly instantiated with portable vector types, like `&[f32x4]`, where instead of using `partial_cmp` of `f32x4` we just fall back to the `PartialOrd` implementation of `&[f32]`.

**Comment by RalfJung** [comment]
> It is surprising to new users: new users often do not expect a lexicographical ordering. 

I fully sympathize. In fact I would expect a pointwise ordering (`x < y` if for all fields, `x[i] < y[i]`), as usually everything in SIMD is pointwise.

**Comment by gnzlbg** [comment]
@RalfJung  

> I fully sympathize. In fact I would expect a pointwise ordering (`x < y` if for all fields, `x[i] < y[i]`), as usually everything in SIMD is pointwise.

The main issue I have with that ordering as the default ordering is that I don't think it is very useful.

Consider `a(0, 1, 2, 3)` and `b(0, 1, 2, 4)`. 

With a lexicographical order, `a < b` is `true`, but with the order you propose, `a < b`, `a == b`, and `a > b` are all false, so vectors of integers do not implement `Ord`, only `PartialOrd`, which in this case returns `None`.

If you had code that works on `&[i32]` and calls sort at some point, and then you change it to use `&[i32x4]`, the first thing you realize is that you can't use `sort` anymore because `i32x4` does not implement `Ord`. One could switch that to use `sort_by(|a,b| a < b)` but it won't really do anything meaningful. 

This behavior, if it is truly what you want, is only a `a.lt(b).all()` away, but I'd rather have no default (that is, no `PartialOrd` implementation), that one that in some cases can be even more surprising than the lexicographical ordering.

**Comment by RalfJung** [comment]
> With a lexicographical order, a < b is true, but with the order you expected a < b, a == b, and a > b are all false, so vectors of integers do not implement Ord, only PartialOrd, which in this case returns None.

Yes, that is exactly what I would expect. Pointerwise ordering is partial.

> If you had code that works on &[i32] and calls sort at some point, and then you change it to use &[i32x4]

Yeah sort works per-element, so how could one expect sorting a vec of SIMD elements to make any sense? The `Ord` implementation you are removing here (lexicographic) also doesn't sort the slice the same way any more as it was sorted with `i32`. If anything I'd see this as an argument in favor of pointwise ordering as it makes such code not compile any more, which is the best possible behavior (better than compiling it but doing something strange).

**Comment by gnzlbg** [comment]
> If anything I'd see this as an argument in favor of pointwise ordering as it makes such code not compile any more, which is the best possible behavior (better than compiling it but doing something strange).

Yeah, I'll add this to the disadvantages of having a lexicographical ordering be the default.

**Comment by gnzlbg** [comment]
So I've sent a PR that removes the `PartialOrd` and `Ord` implementations.

The vectors that can be partially ordered have a `vec::partial_ord(&self)` method that returns a wrapper that implements `PartialOrd`, and when possible, `Ord`. 

The vectors that can be totally ordered have a `vec::ord(&self)` method that returns a wrapper that implements `Ord`.
