### ISSUE TITLE
u128xN casts missing

### ISSUE THREAD

**Issue by TheIronBorn** [rust-lang-nursery/packed_simd#49]
Any particular reason for this?

(It speeds up a component of rand's [`UniformInt`](https://github.com/rust-lang-nursery/rand/pull/561) by up to x2. We could implement it with the platform intrinsic but that's not ideal)

**Comment by gnzlbg** [comment]
Its probably just an oversight, the `_128xN` types are new.

**Comment by gnzlbg** [comment]
Which casts are missing here? They do look correct to me.
