### ISSUE TITLE
vector scatters broken on mips 32-bit

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/packed_simd#85]
The portable vector scatter test fail on `mips-unknown-linux-gnu` and `mipsel-unknown-linux-gnu`: 

```shell
---- vPtr::ptr_mut_x2_write::write stdout ----
thread 'vPtr::ptr_mut_x2_write::write' panicked at 'assertion failed: `(left == right)`
  left: `[0, 1]`,
 right: `[42, 42]`', src/vPtr.rs:10:1
```

**Comment by draganmladjenovic** [comment]
@gnzlbg  Sorry for not noticing this sooner. Is this still happening ?

**Comment by gnzlbg** [comment]
@draganmladjenovic I think we haven't upgraded LLVM since this was filled so it should be happening. To reproduce this, one should just remove the `#[cfg(target_arch = "mips")]` path here and try to use the `simd_scatter` intrinsic for it: https://github.com/rust-lang-nursery/packed_simd/blob/f00ef3f59d79f418e99eb56fbff566810189e67e/src/api/ptr/gather_scatter.rs#L119

**Comment by gnzlbg** [comment]
Thanks for the update!

**Comment by draganmladjenovic** [comment]
Hi @gnzlbg, I submitted the patch at https://reviews.llvm.org/D52045. I'm fairly certain that it won't go in 7.0 maybe 7.0.1 .

**Comment by gnzlbg** [comment]
Thanks! Can you let me know when the patch gets merged? rustc now follows LLVM-trunk pretty closely, so we don't have to wait for an LLVM release to benefit from it :)

**Comment by GabrielMajeri** [comment]
@gnzlbg The patch has been merged into LLVM trunk:https://reviews.llvm.org/rL342884

**Comment by nikic** [comment]
As this has been merged long ago and LLVM has been updated since, can this issue be closed?

**Comment by gnzlbg** [comment]
We still have workarounds for this bug in `packed_simd` (e.g. https://github.com/rust-lang-nursery/packed_simd/blob/60ca4eff21cb9cecad17b28a98f87b0b9148e563/src/api/ptr/gather_scatter.rs#L139). I'd prefer for a PR that removes those workarounds to close this issue.
